### ISSUE TITLE
Error message: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KbWorks** [akumidv/tradingview-assistant-chrome-extension#27]
Hi When running the optimiser the first run seems to run the second raises this error .

Error message: Cannot convert undefined or null to object

<p>An error has occurred.

Reload the page and try again.
You can describe the problem by following <a href="https://github.com/akumidv/tradingview-assistant-chrome-extension/issues" target="_blank" rel="noopener">the link</a>.

Error message: Cannot convert undefined or null to object</p>

**Comment by akumidv** [comment]
Can you take screenshot with open console in developer mode? For this you need to press F12 and click on console tab. Without this information I can't understand whats wrong.
On console will be showed the error messages with place where it happened  (if you would expand the error it will be very helpful)

**Comment by KbWorks** [comment]
![image](https://user-images.githubusercontent.com/14150615/171579400-c9b00f74-d9d1-453e-9599-a006f20cb6c0.png)

**Comment by akumidv** [comment]
Thanks for this full description. It is very useful. As I see on your screenshot  the problem there in broken parsing process. The extension can parse report table. So because there none of data present it generate an error that can't convert empty data.
It can't parse data because can't set variables with new selectors (an error with `Identefer has already been declared`. 
The possible reason of this you don't turn off the extension from Chrome story and install extension from repository. If you switch off or delete on of them I hope all be ok. If not take a new screenshots please after this changes.
![image](https://user-images.githubusercontent.com/12490281/172094303-f85087e2-6323-44df-a4ae-0d1ee68cb863.png)

Extension that was switched off for example
![image](https://user-images.githubusercontent.com/12490281/172094821-5b7d8494-c103-44cb-8e6e-40a8966c540f.png)

**Comment by KbWorks** [comment]
I think that was the problem it is working now.
