### ISSUE TITLE
No param detected

### ISSUE THREAD

**Issue by r4m0np** [akumidv/tradingview-assistant-chrome-extension#34]
![image](https://user-images.githubusercontent.com/38972361/173248738-6dedfe69-b912-46f4-a696-07918a454dde.png)
![image](https://user-images.githubusercontent.com/38972361/173248747-01547b29-f261-4909-bcc0-d49f66527cc1.png)

**Comment by akumidv** [comment]
I guess the problem is in chart parameters. On your screenshoot (firest screenshot the strategy tab do not have tabs and strategy name (second screenshot)
![image](https://user-images.githubusercontent.com/12490281/173274366-8780594b-25e5-4dcb-b71c-8ea9a3c017d3.png)

![image](https://user-images.githubusercontent.com/12490281/173276252-954cece4-6584-40f3-b64f-a548859347b4.png)
